name: sshguard-robertliu
version: '2.4.0+0'
summary: Protects from brute force attacks against ssh
description: |
  sshguard protects hosts from brute-force attacks against SSH and other services.
  It aggregates system logs and blocks repeat offenders using one of several 
  firewall backends, including iptables, ipfw, and pf.

    This snap does not have the capability to auto-connect the required
    interfaces. Please use the following commands to do so:
      $ sudo snap connect sshguard-robertliu:firewall-control
      $ sudo snap connect sshguard-robertliu:log-observe
      $ sudo snap restart sshguard-robertliu

grade: stable
confinement: strict

apps:
    sshguard:
        command: bin/sshguard
        daemon: simple
        plugs: [firewall-control, log-observe]

parts:
    common:
        plugin: dump
        source: .
        organize:
            confs/: etc/sshguard/
        prime:
            - bin
            - etc

    sshguard:
        plugin: autotools
        source: https://bitbucket.org/sshguard/sshguard.git
        source-type: git
        source-branch: v2.4.0
        source-depth: 1
        build-packages:
            - byacc
            - flex
            - python-docutils
        override-build: |
            echo 'patching sshguard ...'
            sed -i 's/libexec="@libexecdir@"/libexec="\$SNAP@libexecdir@"/' src/sshguard.in
            sed -i 's/config="@sysconfdir@\/sshguard.conf"/config="\$SNAP_DATA\/sshguard.conf"/' src/sshguard.in
            snapcraftctl build
        prime:
            - libexec/sshg-blocker
            - libexec/sshg-fw-iptables
            - libexec/sshg-logtail
            - libexec/sshg-parser
            - sbin/sshguard
            - share

